version: '3.9'

networks:
  default:
    name: observability
    driver: bridge

services:
  # ******************
  # Core Services
  # ******************

  # OpenTelemetry Collector
  # otelcol:
  #   image: otel/opentelemetry-collector-contrib:0.74.0
  #   container_name: otel-col
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 125M
  #   restart: unless-stopped
  #   command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-extras.yml" ]
  #   volumes:
  #     - ./src/otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
  #     - ./src/otelcollector/otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
  #   ports:
  #     - "4317"          # OTLP over gRPC receiver
  #     - "4318:4318"     # OTLP over HTTP receiver
  #     - "9464"          # Prometheus exporter
  #     - "8888"          # metrics endpoint
  #   depends_on:
  #     - jaeger
  #   logging: *logging

  # Generate fake traces
  # k6-tracing:
  #   image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
  #   environment:
  #     - ENDPOINT=otel-collector:4317
  #   restart: always
  #   depends_on:
  #     - otel-collector

  # OTEL collector pipeline
  otel-collector:
    image: otel/opentelemetry-collector:0.61.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317"          # OTLP over gRPC receiver
      - "4318"     # OTLP over HTTP receiver

  # ********************
  # Telemetry Components
  # ********************
  # Loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    user: "0"
    command: 
      - "-config.file=/etc/loki.yaml"
    volumes:
      - ./config/loki.yaml:/etc/loki.yaml
      - ./loki-data:/tmp/loki
    ports:
      - "3100:3100"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  # Tempo
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"    # tempo
      - "4317:4317"    # otlp grpc
      - "4318:4318"    # otlp http
    depends_on:
      - loki
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  # Grafana
  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    volumes:
      - ./config/grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ./config/grafana/dashboards-provisioning/:/etc/grafana/provisioning/dashboards/
      - ./config/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
      - prometheus
