# Document for otel-collector
#   https://opentelemetry.io/docs/collector/configuration
# For detailed configuration:
#   Receiver:  https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
#   Processor: https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor
#   Exporter:  https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter
# Extra component lists:
#   Receiver:  https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver
#   Processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor

extensions:
  health_check:

receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  # # Data sources: logs
  # fluentforward:
  #   endpoint: 0.0.0.0:24224
  # # Data sources: metrics
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: otel-collector
  #         scrape_interval: 5s
  #         static_configs:
  #           - targets: [localhost:8888]

processors:
  batch:
    timeout: 1s
    send_batch_size: 50
  tail_sampling:
    # best practice: `decision_wait` * `traces_per_sec` = 2 * `num_traces`
    decision_wait: 5s
    num_traces: 1000
    expected_new_traces_per_sec: 100
    policies:
      [          
        {
          name: errors-policy,
          type: status_code,
          status_code: {status_codes: [ERROR]}
        },
        {
          name: randomized-policy,
          type: probabilistic,
          probabilistic: {sampling_percentage: 25}
        }
      ]

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  logging:
      loglevel: debug

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, tail_sampling]
      exporters: [otlp, logging]
  # telemetry:
  #   logs:
  #     level: debug
